### PR TITLE
Fix and test .timeout() and .retry()

### LINKED ISSUE #14: Timeout doesn't seem to work
calling Frisby.timeout(5000) to set a timeout is not working for me.  The default of 2000 always happens.

Its possible to pass in a timeout to Mocha via file or the command line but I'd prefer to just set it here if possible.

### PR DESCRIPTION
**Pull request by paulmelnikow**
This need came up in badges/shields#1115. We don't have a global mocha timeout configured, so we're using the default of 2000. IcedFrisby's default is 5000 which seems more reasonable for what we're doing, though it's not being passed to Mocha.

Since IcedFrisby registers the Mocha test, it seems reasonable that IcedFrisby's notions of timing should prevail.

If a developer needs a longer timeout, they can just invoke e.g. `timeout(10000)` to set it to a higher value.

If a developer wants the 2000 ms timeout they had before this change, they can run `globalSetup`.

----

Change summary:

- Retry on errors, not just timeouts
- Back off between retries
- Global setup respects `retryBackoff` option
- Configure Mocha’s timeout to accommodate `.timeout()` and `.retry()`

Close #14

### CODE REVIEW

**Comment by paulmelnikow** [comment]
This fixes #14!

File: lib/icedfrisby.js [hunk 1]
```diff
@@ -1142,6 +1142,12 @@ class Frisby {
   }
 
 
+  _mochaTimeout () {
+    return (1 + this.current.retry) * this._timeout +
```
Comment (MarkHerhold) [inline lib/icedfrisby.js]: I understand the next line, but why are we adding `retry * timeout` to that?

Comment (paulmelnikow) [reply lib/icedfrisby.js]: This is the way I'm thinking of it.

If one retry is allowed, you need:

timeout interval for first request + retry backoff + timeout interval for second request

2 (timeout) + 1 (retry backoff)

Does that make sense?

Comment (MarkHerhold) [reply lib/icedfrisby.js]: That does make sense, thanks.

Comment (paulmelnikow) [reply lib/icedfrisby.js]: I'll add that explanation in a comment.

Comment (paulmelnikow) [reply lib/icedfrisby.js]: Come to think of it, it seems clearer factored like this: 840c6c1.

**Comment by MarkHerhold** [comment]
I'm OK with this PR and think it makes sense given issue #14 👍 
A test would be nice, but it's sorta convoluted. I guess we could test to see that IcedFrisby fails within a certain time period and use sinon to count the number of retries?

**Comment by paulmelnikow** [comment]
Yea, IIRC we have no test coverage on any of this code, and it would be nice to have some. (#41)

Your suggestions make sense. We could also use sinon to mock `request`.

Also, at a dumber level we could check that the `timeout` is set correctly on the Mocha test.

File: lib/icedfrisby.js [hunk 2]
```diff
@@ -557,10 +556,7 @@ class Frisby {
           time: diff
         }
 
-        // call caller's callback
-        if (cb && typeof cb === "function") {
-          cb(self.current.response)
-        }
+        cb()
```
Comment (paulmelnikow) [inline lib/icedfrisby.js]: This function invoked from `this._makeRequest()`, which of course has access to `this.current`, so there's no need for this check nor the parameter.

File: lib/icedfrisby.js [hunk 3]
```diff
@@ -1271,11 +1316,9 @@ class Frisby {
       try {
         this.current.expects[i].call(null)
       } catch (e) {
-        if (false === this._exceptionHandler) {
-          this.current.failures.push(e)
+        const shouldStop = this._noteExpectationFailed(e)
+        if (shouldStop) {
           break
-        } else {
-          this._exceptionHandler.call(this, e)
```
Comment (paulmelnikow) [inline lib/icedfrisby.js]: Factored this out rather than duplicating it. New code is equivalent to old code.

File: lib/icedfrisby.js [hunk 4]
```diff
@@ -159,7 +159,7 @@ class Frisby {
       after: [],
       finally: [],
       retry: clone.retry || 0,
-      retry_backoff: clone.retry_backoff || 1000,
+      retryBackoff: clone.retryBackoff || clone.retry_backoff || 1000,
```
Comment (paulmelnikow) [inline lib/icedfrisby.js]: Change to camel-case for consistency. I'm not sure when `retry_backoff` last worked or if it ever worked, so this alias may be unnecessary. Doesn't matter to me either way.

File: lib/icedfrisby.js [hunk 5]
```diff
@@ -1225,31 +1235,54 @@ class Frisby {
 
 
   _makeRequest (done) {
```
Comment (paulmelnikow) [inline lib/icedfrisby.js]: This is completely rewritten. Easier to compare in split view. Factored out `maybePerformRetry` to avoid duplication.

File: lib/icedfrisby.js [hunk 6]
```diff
@@ -1225,31 +1235,54 @@ class Frisby {
...
+    const requestTimeoutId = setTimeout(handleRequestTimeout, this._timeout)
+
+    this.current.it(() => {
+      if (requestAlreadyTimedOut) {
+        return
+      }
+
+      clearTimeout(requestTimeoutId)
+
+      if (this.current.response.status >= 500 && maybePerformRetry()) {
```
Comment (paulmelnikow) [inline lib/icedfrisby.js]: This changes our retry behavior. Instead of retrying only on timeouts, we're also retrying on server errors – i.e. errors which are not related ot the request. Does that make sense?

**Comment by paulmelnikow** [comment]
Have updated the PR title and top comment based on what this now is doing.

**Comment by paulmelnikow** [comment]
@MarkHerhold Would you have time today to read this?

I know @Fishbowler is itching for a release, so if this is going to take longer, I might just go ahead and do a release, and then release again when it's merged.

Also @Fishbowler you're welcome to read as well!

**Comment by MarkHerhold** [comment]
I'll review this but IMO an extra release never hurts.

File: lib/icedfrisby.js (hunk 2 above)
Comment (MarkHerhold) [reply lib/icedfrisby.js]: having `cb()` without `return` before it always makes me nervous

**Comment by MarkHerhold** [comment]
The tests don't seem quite right to me (I have random timing failures because the deliberate nock delays seem to run too quickly) and I'm going to see if I can take a stab and ensuring that the exception handlers are called.

**Comment by MarkHerhold** [comment]
I adjusted the tests but I can't figure out how to make changes to the PR outside the web editor. While I figure that out, here's a patch I'd like you to consider applying:

```diff
diff --git a/test/frisby_mock_request.js b/test/frisby_mock_request.js
index 742384f..bc389a2 100644
--- a/test/frisby_mock_request.js
+++ b/test/frisby_mock_request.js
@@ -1087,57 +1087,51 @@ describe('Frisby matchers', function() {
 
   describe('timeouts and retries', function () {
     it('should fail when timeout() value elapses', function () {
-      let startTime
+      const timeout = 10
 
       nock('http://example.com')
         .get('/just-dont-come-back-1')
-        .reply((uri, requestBody, callback) => {
-          startTime = process.hrtime()
-          // To simulate a timeout, do not invoke the callback.
-        })
+        .delayBody(50) // delay 50ms
+        .reply(200, '<html></html>')
 
-      const requestTimeoutMillis = 123
+      const spy = sinon.spy()
 
       frisby.create(this.test.title)
         .get('http://example.com/just-dont-come-back-1')
-        .timeout(requestTimeoutMillis)
-        .exceptionHandler(err => {
-          // TODO How can I assert that this method is called?
-
-          // Confidence check
-          expect(startTime).to.be.an('array')
-
-          // Assertion
-          const [seconds, nanoseconds] = process.hrtime(startTime)
-          const endTimeMillis = 1e3 * seconds + 1e-6 * nanoseconds
-
-          const assertionGracePeriodMillis = [5, 50]
-          expect(endTimeMillis).to.be.within(
-            requestTimeoutMillis - assertionGracePeriodMillis[0],
-            requestTimeoutMillis + assertionGracePeriodMillis[1])
+        .timeout(timeout)
+        .exceptionHandler((err) => {
+          spy()
+          expect(err.message).to.equal(`Request timed out after ${timeout} ms`)
+          expect(spy.calledOnce).to.equal(true)
         })
         .toss()
     })
 
     it('should retry the expected number of times after a timeout', function () {
+      const retryCount = 4
       let actualRequestCount = 0
+      const timeout = 5
 
       nock('http://example.com')
         .get('/just-dont-come-back-2')
+        .delayBody(50) // delay 50ms
         .times(5)
         .reply((uri, requestBody, callback) => {
           actualRequestCount += 1
-          // To simulate a timeout, do not invoke the callback.
+          return 200, '<html></html>'
         })
 
-      const retryCount = 4
+      const spy = sinon.spy()
 
       frisby.create(this.test.title)
         .get('http://example.com/just-dont-come-back-2')
-        .timeout(5)
+        .timeout(timeout)
         .retry(retryCount, 0)
         .exceptionHandler(err => {
-          // TODO How can I assert that this method is called?
+          spy()
+          expect(err.message).to.equal(`Request timed out after ${timeout} ms (${retryCount + 1} attempts)`)
+          expect(spy.calledOnce).to.equal(true)
+
           expect(actualRequestCount).to.equal(retryCount + 1)
         })
         .toss()
```

**Comment by MarkHerhold** [comment]
Ah, thanks for the explanation. I agree with your points on the TODOs and think that Promises are likely the best path forward (and the way of `async`/`await`!).

**Comment by MarkHerhold** [comment]
I'm good with this PR now. I think it's about as good as we are going to get without changing more of the underlying implementation.

**Comment by paulmelnikow** [comment]
Thoughts on semver?

> - Retry on errors, not just timeouts

It's possible, though unlikely, that a test would rely on retries for timeouts, while somehow failing when a server error comes back instead. So I go with **non-breaking feature**.

> - Back off between retries

**Bug fix**

> - Global setup respects `retryBackoff` option

**Bug fix**

> - Configure Mocha’s timeout to accommodate `.timeout()` and `.retry()`

Could cause test timeouts if people are relying on a generous global timeout which we're now clamping down. Hmm. **Breaking change?**

Maybe we should modify this to use the max of the global timeout and our computed timeout. Then it would be a **non-breaking feature**.

**Comment by MarkHerhold** [comment]
To me, test-specific timeouts should override global timeouts. I'd rather just ship a minor version than add more logic that could be confusing to users later on.

**Comment by paulmelnikow** [comment]
I'm fine with that. Hopefully it won't cause problems!
